In [1]:
from keras.preprocessing import image

In [1]:
import cv2

In [2]:

import cv2
import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import keras
import tensorflow as tf
from sklearn.metrics import confusion_matrix
import seaborn as sns
from sklearn.metrics import classification_report

In [4]:
with_mask='with_mask'
without_mask='without_mask'

In [5]:
pd.DataFrame([len(os.listdir(with_mask)),len(os.listdir(without_mask))],columns=['Number'],index=['with_mask','without_mask'])

Number
with_mask       3725
without_mask    3828

In [3]:
categories = ['with_mask', 'without_mask']

In [4]:
data = []
for category in categories:
    path = os.path.join(category)
    # print(path)
    label = categories.index(category)
    for file in os.listdir(path):
        
        img_path = os.path.join(path, file)
        img =cv2.imread(img_path)
        img = cv2.resize(img,(224,224))
        
        data.append([img,label])

In [5]:
len(data)

7553

In [8]:
from random import sample

data1 = sample(data,2000)

len(data1)

2000

In [12]:
import random

In [19]:
random.shuffle(data1)

In [20]:
X =[]
Y =[]

for features, label in data1:
    X.append(features)
    Y.append(label)

In [21]:
len(X)

2000

In [22]:
len(Y)

2000

In [23]:
X = np.array(X)
Y = np.array(Y)

In [24]:
X.shape

(2000, 224, 224, 3)

In [25]:
Y


array([1, 0, 1, ..., 1, 1, 0])

In [26]:
X = X/255

In [27]:
X[0]

array([[[0.48627451, 0.50980392, 0.52941176],
        [0.47058824, 0.49411765, 0.51372549],
        [0.45490196, 0.4745098 , 0.49411765],
        ...,
        [0.38823529, 0.33333333, 0.35686275],
        [0.38039216, 0.32941176, 0.35294118],
        [0.37647059, 0.32941176, 0.35294118]],

       [[0.47843137, 0.50196078, 0.52156863],
        [0.46666667, 0.48627451, 0.50588235],
        [0.44705882, 0.46666667, 0.48627451],
        ...,
        [0.39215686, 0.3372549 , 0.36078431],
        [0.38431373, 0.33333333, 0.35686275],
        [0.38039216, 0.33333333, 0.35686275]],

       [[0.46666667, 0.49019608, 0.50980392],
        [0.45490196, 0.4745098 , 0.49411765],
        [0.43529412, 0.45490196, 0.47058824],
        ...,
        [0.39607843, 0.34117647, 0.36470588],
        [0.38823529, 0.3372549 , 0.36078431],
        [0.38431373, 0.3372549 , 0.36078431]],

       ...,

       [[0.11764706, 0.15294118, 0.16862745],
        [0.11372549, 0.14901961, 0.16470588],
        [0.11372549, 0

this is another approach to solve the concatation problem

In [6]:
# label=[]
# data=[]
# size=[]
# #with mask label 1
# for img in os.listdir(with_mask):
#     img_arr=cv2.imread(os.path.join(with_mask,img))
#     data.append(img_arr)
#     label.append(1)
#     size.append(img_arr.shape)
# #without mask label 0
# for img in os.listdir(without_mask):
#     img_arr=cv2.imread(os.path.join(without_mask,img))
#     data.append(img_arr)
#     label.append(0)
#     size.append(img_arr.shape)

In [7]:
# pd.DataFrame(pd.Series(size).value_counts(),columns=['Number']) 

Number
(225, 225, 3)     664
(428, 320, 3)     381
(275, 183, 3)     255
(100, 100, 3)     207
(183, 275, 3)     181
...               ...
(192, 127, 3)       1
(218, 218, 3)       1
(422, 759, 3)       1
(413, 600, 3)       1
(135, 156, 3)       1

[2692 rows x 1 columns]

In [8]:
# #Resize Image
# Size=224
# for x in range(len(data)):
#     data[x]=cv2.resize(data[x],(Size,Size))

In [9]:
# data[100].shape

AttributeError: 'list' object has no attribute 'shape'

In [10]:
# len(data)

7553

In [11]:
# import random 

In [12]:
# random.shuffle(data)

In [13]:
# data=np.array(data)
# label=np.array(label)


In [14]:
# data = data/255

In [15]:
# data[0]

array([[[ 16,  17,  21],
        [ 16,  17,  21],
        [ 15,  15,  20],
        ...,
        [ 15,  16,  14],
        [ 15,  16,  14],
        [ 15,  16,  14]],

       [[ 15,  16,  20],
        [ 15,  16,  20],
        [ 14,  14,  19],
        ...,
        [ 15,  16,  14],
        [ 15,  16,  14],
        [ 15,  16,  14]],

       [[ 14,  14,  19],
        [ 14,  14,  19],
        [ 13,  13,  19],
        ...,
        [ 15,  16,  14],
        [ 15,  16,  14],
        [ 15,  16,  14]],

       ...,

       [[199, 207, 212],
        [199, 207, 212],
        [199, 207, 212],
        ...,
        [119, 135, 162],
        [119, 135, 161],
        [119, 135, 161]],

       [[198, 206, 208],
        [198, 206, 208],
        [198, 207, 209],
        ...,
        [120, 135, 163],
        [120, 135, 163],
        [120, 135, 163]],

       [[198, 206, 206],
        [198, 206, 206],
        [198, 207, 208],
        ...,
        [121, 135, 163],
        [121, 135, 163],
        [121, 135, 163]]

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=.30,random_state=44)
print('X Train Shape is :',X_train.shape)
print('X Test Shape is :',X_test.shape)
print('Y Train Shape is :',y_train.shape)
print('Y Test Shape is :',y_test.shape)

X Train Shape is : (1400, 224, 224, 3)
X Test Shape is : (600, 224, 224, 3)
Y Train Shape is : (1400,)
Y Test Shape is : (600,)


In [29]:
import keras
from keras.applications.vgg16 import VGG16

In [30]:
vgg = VGG16()

In [31]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [32]:
from keras import Sequential

In [33]:
model = Sequential()

In [34]:
for layer in vgg.layers[:-1]:
    model.add(layer)

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [36]:
for layer in model.layers:
    layer.trainable = False

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [38]:
from keras.layers import Dense

In [39]:
model.add(Dense(1,activation = "sigmoid"))

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [41]:
model.compile(optimizer ="Adam",loss = "binary_crossentropy", metrics=["accuracy"])

In [42]:
model.fit(X_train, y_train,epochs=5,validation_data=(X_test, y_test))

Epoch 1/5
44/44 [==============================] - 273s 6s/step - loss: 0.6078 - accuracy: 0.6750 - val_loss: 0.4704 - val_accuracy: 0.8300
Epoch 2/5
44/44 [==============================] - 284s 7s/step - loss: 0.4457 - accuracy: 0.8307 - val_loss: 0.4008 - val_accuracy: 0.8250
Epoch 3/5
44/44 [==============================] - 305s 7s/step - loss: 0.3799 - accuracy: 0.8550 - val_loss: 0.3467 - val_accuracy: 0.8800
Epoch 4/5
44/44 [==============================] - 332s 8s/step - loss: 0.3188 - accuracy: 0.8914 - val_loss: 0.3218 - val_accuracy: 0.8933
Epoch 5/5
44/44 [==============================] - 309s 7s/step - loss: 0.2919 - accuracy: 0.9007 - val_loss: 0.2956 - val_accuracy: 0.8917


In [44]:
model.save('model.h5')

In [ ]:
cap = cv2.VideoCapture(0)

In [ ]:
while True:
    ret, frame = cap.read()
    # call the detection method
    frame = cv2.resize(frame,(224,224))
    
    cv2.imshow("window", frame)
    
    if cv2.waitKey(1) & 0xFF == ord ('x'):
        break
    
cv2.destroyAllWindows()

In [ ]:
def detect_face_mask(img):
    
    y_pred = model.predict(img.reshape(1,224,224,3))
    
    return y_pred

In [ ]:
sample1 = cv2.imread('without_mask\without_mask_1.jpg')

sample1 = cv2.resize(sample1,(224,224))

In [ ]:
detect_face_mask(sample1)